# Disabled cache in hope of improving reliability of AppVeyor builds
cache: []
# - "c:\\sr" # stack root, short paths == fewer problems
# - "c:\\sr\\build-plan"
# - "c:\\sr\\build-plan-cache"
# - "c:\\sr\\config.yaml"
# - "c:\\sr\\global-project"
# - "c:\\sr\\indices"
# - "c:\\sr\\precompiled"
# - "c:\\sr\\programs"
# - "c:\\sr\\setup-exe-cache"
# - "c:\\sr\\snapshots"
# - "c:\\sr\\templates"
# - "C:\\stack\\.stack-work\\downloaded"
# - "C:\\stack\\.stack-work\\install"
# - "C:\\stack\\.stack-work\\logs"

install:
- git clone -q --branch=master https://github.com/literate-unitb/literate-unitb-logic.git c:\\stack\\code
- cd code
- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"
  matrix: 
    # - lts: --resolver lts-3
    # - lts: --resolver lts-6
    # - lts: --resolver lts-7
    - lts: ""

platform:
  # - x86
  - x64
 
build:
  parallel: true

build_script:
- stack setup %lts% > nul
- cmd: echo "" | stack --no-terminal install lens %lts% --no-run-tests
- cd ..
- dir
- dir code
- 7z a cache-%platform%.7z c:\\stack\\code\\.stack-work c:\\sr
- dir

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token: 
    secure: 7Nj4tTtmF2gke6WRsKmZG7l58G6Ue5Yw29DucWAgq3Ea34iuYCyZSpl7T7EezB5z # your encrypted token from GitHub
  artifact: c:\\stack\\cache-%platform%.7z   # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    # appveyor_repo_tag: true        # deploy on tag push only

test_script:
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
# - cmd: echo "" | stack --no-terminal test %lts%
- cmd: echo ""
